VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "AlfrescoAsset"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

Public ISBN As String
Public FILE_TYPE As String
Public FILE_NAME As String
Public ACCESS_USER As String
Public ITEM_TYPES As Collection
Public NOTES As String
Public ACCESS_TYPE As String
